name: dvm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ^3.16.8

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  slidex:
    path: packages/slidex

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  yumemi_lints: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
