name: dvm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ^3.16.8

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^1.4.0

flutter:
  uses-material-design: true
